# Generated by Django 4.2.9 on 2024-01-24 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=200)),
                ('license_plate_num', models.CharField(max_length=50)),
                ('max_passenger_num', models.IntegerField()),
                ('special_vehicle_info', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('expected_arrival_time', models.DateTimeField()),
                ('num_passengers', models.IntegerField(default=1)),
                ('vehicle_type', models.CharField(blank=True, max_length=200)),
                ('special_request', models.TextField(blank=True)),
                ('can_share', models.BooleanField()),
                ('is_open', models.BooleanField()),
                ('is_complete', models.BooleanField()),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ride_sharing.driver')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(verbose_name='date registered')),
            ],
        ),
        migrations.CreateModel(
            name='ShareRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sharer', models.IntegerField(default=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride_sharing.request')),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride_sharing.user')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride_sharing.user'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride_sharing.user'),
        ),
    ]
